version: 0.9.{branch}.{build}.

clone_depth: 10
shallow_clone: true
cache: '%LOCALAPPDATA%\\Yarn'
build:
  verbosity: minimal

install:
  # yarn issue with cross-env
  - npm install --global cross-env
  - yarn install

build_script:
  - yarn run build
  - yarn run dist

test_script:
  - cmd: test:ci-on-windows

deploy: off
