################################################################################
# Travis CI configuration
# Docs: https://docs.travis-ci.com/
# About Stages: https://docs.travis-ci.com/user/build-stages/
#
sudo: false
dist: trusty

# https://docs.travis-ci.com/user/notifications/
notifications:
  email: false


# https://docs.travis-ci.com/user/caching/
cache:
  directories:
    - node_modules
  timeout: 180
  yarn: true

################################################################################
# Templates
templates:
  - &tmpl-common-setup
    # You can choose Node.js and io.js versions to run your tests
    # by adding them to the node_js section of your .travis.yml:
    # docs: https://docs.travis-ci.com/user/languages/javascript-with-nodejs#Choosing-Node-versions-to-test-against
    language: node_js
    node_js:
      - node
    install: yarn install
  - &tmpl-ssh-setup
    before_install:
      - |
       declare -r SSH_FILE="$(mktemp -u $HOME/.ssh/XXXXX)"

       openssl aes-256-cbc \
         -K $encrypted_f67124605cd2_key \
         -iv $encrypted_f67124605cd2_iv \
         -in $TRAVIS_BUILD_DIR/devel/travis_ssh_key.enc \
         -out "$SSH_FILE" -d

       chmod 600 "$SSH_FILE" \
         && printf "%s\n" \
              "Host github.com" \
              "  IdentityFile $SSH_FILE" \
              "  LogLevel ERROR" >> ~/.ssh/config

       git config user.email "howi@okramlabs.com"
       git config user.name "howibot"

# defaults
before_install: skip
install: skip
before_script: skip
script: skip
after_success: skip
after_failure: skip
after_script: skip

################################################################################
# stages
stages:
  # lint and test
  - name: lint and test
    # if: (type = pull_request) AND (branch = master)
    if: (push, pull_request) AND (branch = master)
  # build site
  - name: push to okramlabs fork
    if: (repo = mkungla/aframe-webpack-boilerplate) AND (type = push) AND (branch = master OR tag IS present)
  # deploy okramlabs.github.io
  - name: deploy staging
    if: (repo = mkungla/aframe-webpack-boilerplate) AND (type = push) AND (branch = master) AND (NOT tag IS present)
  # deploy okramlabs.github.io (only on tags on upstream)
  - name: deploy production
    if: (repo = mkungla/aframe-webpack-boilerplate) AND (NOT type = pull_request) AND (tag IS present)

################################################################################
# jobs
jobs:
  include:
    # verify A-Frame pull request
    - stage: lint and test
      env: JOB_NAME=lint
      <<: *tmpl-common-setup
      script: yarn run lint
    # run primary tests
    - <<: *tmpl-common-setup
      env: JOB_NAME=test:ci-on-linux
      script: yarn run test:ci-on-linux
      # Do something when everything was successful!
      after_success:
        # For example here we upload covergae report to codacy
        - cat ./devel/coverage/lcov.info | node_modules/.bin/codacy-coverage --token $CODACY_PROJECT_TOKEN
    # build A-Frame
    - stage: push to okramlabs fork
      <<: *tmpl-okramlabs-setup
      script:
        - git remote add github/okramlabs git@github.com:okramlabs/aframe-webpack-boilerplate.git
        - git fetch github/okramlabs
        - git checkout -b push-to-okramlabs $TRAVIS_COMMIT
        - git rebase -i github/okramlabs/master
        - git push github/okramlabs master
    # deploy preview
    - stage: deploy staging
      <<: *tmpl-ssh-setup
      <<: *tmpl-common-setup
      script: echo "deploy staging"
      before_deploy: echo "before_deploy okramlabs.github.src"
      deploy:
        skip_cleanup: true
        provider: script
        script:
          - git remote add github/okramlabs git@github.com:okramlabs/aframe-webpack-boilerplate.git
          - git fetch github/okramlabs
          - git checkout -b push-to-okramlabs $TRAVIS_COMMIT
          - git push github/okramlabs gh-pages
        on:
          branch: master
      after_deploy: echo "after_deploy okramlabs.github.src"
    # deploy new release + npm package
    - stage: deploy production
      <<: *tmpl-ssh-setup
      <<: *tmpl-common-setup
      script: echo "deploy production"
      before_deploy: echo "before_deploy production"
      deploy:
        skip_cleanup: true
        provider: script
        script:
          - git checkout -b gh-pages
          - git push origin gh-pages
        on:
          branch: master
      after_deploy: echo "create new release production (create new release)"

# Your before scripts
# You can run custom commands before the installation step (before_install),
# and before (before_script) or after (after_script) the script step.
# docs: https://docs.travis-ci.com/user/customizing-the-build#The-Build-Lifecycle
# before_script:
#   - export DISPLAY=:99.0
#   - sh -e /etc/init.d/xvfb start
