# https://circleci.com/docs/2.0/configuration-reference/
version: 2

# jobs
jobs:
  build-staging:
    macos:
      xcode: "9.0"
    steps:
      - checkout
      - run:
          name: install dependencies
          command: yarn install
      - run:
          name: build staging
          command: yarn run build
  build-dist:
    macos:
      xcode: "9.0"
    steps:
      - checkout
      - run:
          name: install dependencies
          command: yarn install
      - run:
          name: build dist
          command: yarn run build

  test:
    macos:
      xcode: "9.0"
    steps:
      - checkout
      - run:
          name: install dependencies
          command: yarn install
      - run:
          name: run mac tests
          command: yarn run test:ci-on-mac

# Workflow configuration
workflows:
  version: 2
  member-push:
    jobs:
      - build-staging
      - build-dist
      - test:
          requires:
            - build-staging
            - build-dist
          filters:
            branches:
              only:
                - master
                - /hotfix-.*/
